TAG: 'CARLA_perception'

GPUS: [0] 
BATCHSIZE: 8 # 
PRECISION: 16
EPOCHS: 15

N_WORKERS: 8

DATASET:
  NAME: 'carla'

TIME_RECEPTIVE_FIELD: 3
N_FUTURE_FRAMES: 0

IMAGE:
  FINAL_DIM: (128, 256)
  ORIGINAL_HEIGHT: 160
  ORIGINAL_WIDTH: 320

LIFT:
  X_BOUND: [-25.0, 25.0, 0.25] 
  Y_BOUND:  [-25.0, 25.0, 0.25] 
  GT_DEPTH: True 

MODEL:
  ENCODER:
    NAME: 'efficientnet-b4'
    USE_DEPTH_DISTRIBUTION: True
  TEMPORAL_MODEL:
    NAME: 'temporal_block'
    INPUT_EGOPOSE: True
  BN_MOMENTUM: 0.05

SEMANTIC_SEG:
  VEHICLE:
    ENABLED: True 
  HEATMAP:
    ENABLED: False
  PEDESTRIAN:
    ENABLED: True
  HDMAP:
    ENABLED: True


INSTANCE_SEG:
  ENABLED: True

INSTANCE_FLOW:
  ENABLED: False

PROBABILISTIC:
  ENABLED: False

PLANNING:
  ENABLED: False

OPTIMIZER:
  LR: 1e-3